services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ambev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
 
  rabbitmq:
    image: rabbitmq:4-management
    networks:
      - microservices-network    
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação do RabbitMQ (AMQP)
      - "15672:15672" # Painel de administração do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest # Usuário padrão
      RABBITMQ_DEFAULT_PASS: guest # Senha padrão 

  # api_ambev_sale:
  #   image: api_ambev_sale           
  #   ports:
  #     - "5001:80"
  #   depends_on:
  #     - postgres

  api:
    build:
      context: .
      dockerfile: src/Ambev.Sale.WebApi/Dockerfile
    container_name: Ambev.WebApi.Sale
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:        
      - ASPNETCORE_ENVIRONMENT=Development
      #- ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Username=admin;Password=root;Database=ambev;
    ports:
      - "5000:5000"
      - "5001:5001" 

  # angular:
  #   build:
  #     context: ./MeuAppAngular
  #     dockerfile: Dockerfile
  #   container_name: meu_app_angular
  #   restart: always
  #   depends_on:
  #     - api
  #   ports:
  #     - "80:80"

volumes:
  postgres_data:
